"use client";

import { FormEvent, ReactNode, useEffect, useRef, useState } from "react";
import { Activity, ArrowUp, BarChart3, Bot, Check, ChevronRight, CircleDot, Database, FileText, FolderUp, Menu, Plus, Search, ShieldCheck, Sparkles, Upload, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";

type View = "research" | "evaluation" | "ingestion";
type Source = { content: string; source: string };
type Message = { role: "assistant" | "user"; content: string; sources?: Source[]; plan?: string[] };
type Dataset = { rag_samples: { id: number; question: string; domain: string }[]; guardrails_samples: { id: string; input: string; expected_blocked: boolean }[] };
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const welcome: Message = { role: "assistant", content: "Choose a question or write your own. I’ll show every stage of the research process and attach the source material used to answer." };
const suggestions = ["How do CronJobs handle Pod restarts?", "Explain the difference between HPA and VPA.", "What does kube-apiserver do?"];

export default function Home() {
  const [view, setView] = useState<View>("research");
  const [sidebarOpen, setSidebarOpen] = useState(true);
  return <main className="min-h-screen bg-[#0a0f17] text-stone-100 selection:bg-rose-200 selection:text-stone-950">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[250px] flex-col border-r border-stone-800 bg-[#0d131d] p-4 transition-transform duration-300 ${sidebarOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between px-2 py-2"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-rose-300/25 bg-rose-300/10 text-rose-100"><Sparkles size={17} /></span><div><p className="text-sm font-semibold">Atlas</p><p className="text-xs text-stone-500">Knowledge operations</p></div></div><Button variant="ghost" size="icon" onClick={() => setSidebarOpen(false)} aria-label="Close sidebar"><X size={18} /></Button></div>
      <Button variant="outline" className="mt-7 justify-start border-stone-700 bg-stone-900/40 text-stone-300 hover:bg-stone-800 hover:text-white" onClick={() => setView("research")}><Plus size={16} /> New research</Button>
      <nav className="mt-8 space-y-1" aria-label="Workspace navigation"><NavItem active={view === "research"} icon={<Search size={16} />} label="Research" onClick={() => setView("research")} /><NavItem active={view === "evaluation"} icon={<BarChart3 size={16} />} label="Evaluations" onClick={() => setView("evaluation")} /><NavItem active={view === "ingestion"} icon={<FolderUp size={16} />} label="Ingest documents" onClick={() => setView("ingestion")} /></nav>
      <div className="mt-auto rounded-xl border border-stone-800 bg-stone-900/60 p-3.5"><div className="flex items-center gap-2 text-sm font-medium"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-60" /><span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400" /></span> Pipeline ready</div><p className="mt-2 text-xs leading-5 text-stone-500">Guardrails, vector search, reranking, and answer synthesis.</p></div>
    </aside>
    <div className={`min-h-screen transition-[padding] duration-300 ${sidebarOpen ? "lg:pl-[250px]" : "lg:pl-0"}`}><header className="sticky top-0 z-30 flex h-[70px] items-center justify-between border-b border-stone-800/80 bg-[#0a0f17]/90 px-5 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={() => setSidebarOpen((open) => !open)} aria-label={sidebarOpen ? "Collapse sidebar" : "Open sidebar"}><Menu size={18} /></Button><div><p className="text-sm font-semibold">{view === "research" ? "Research workspace" : view === "evaluation" ? "Evaluation studio" : "Document intake"}</p><p className="text-xs text-stone-500">Enterprise RAG control room</p></div></div><Badge variant="outline" className="border-stone-700 bg-stone-900 px-2.5 py-1 text-xs font-normal text-stone-400"><ShieldCheck size={13} className="mr-1.5 text-emerald-400" /> Guarded</Badge></header>
      {view === "research" ? <Research /> : view === "evaluation" ? <Evaluation /> : <Ingestion />}
    </div>
  </main>;
}

function NavItem({ active, icon, label, onClick }: { active: boolean; icon: ReactNode; label: string; onClick: () => void }) {
  return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition-colors ${active ? "bg-stone-800 text-white" : "text-stone-500 hover:bg-stone-900 hover:text-stone-200"}`}><span className={active ? "text-rose-200" : ""}>{icon}</span>{label}</button>;
}

function Research() {
  const [messages, setMessages] = useState<Message[]>([welcome]); const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState({ value: 0, label: "Ready" }); const end = useRef<HTMLDivElement>(null);
  const scroll = () => requestAnimationFrame(() => end.current?.scrollIntoView({ behavior: "smooth" }));
  async function ask(event?: FormEvent, supplied?: string) {
    event?.preventDefault(); const question = (supplied ?? input).trim(); if (!question || busy) return;
    setInput(""); setBusy(true); setProgress({ value: 8, label: "Opening secure stream" }); setMessages((all) => [...all, { role: "user", content: question }, { role: "assistant", content: "" }]); scroll();
    try {
      const response = await fetch(`${API_URL}/query/stream`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ q: question, thread_id: "demo-session" }) });
      if (!response.ok || !response.body) throw new Error("Research service unavailable.");
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let text = "";
      const update = (patch: Partial<Message>) => { setMessages((all) => all.map((item, index) => index === all.length - 1 ? { ...item, ...patch } : item)); scroll(); };
      const parse = (block: string) => { const eventType = block.match(/^event:\s*(.+)$/m)?.[1]?.trim(); const raw = block.match(/^data:\s*(.+)$/m)?.[1]; if (!eventType || !raw) return; const data = JSON.parse(raw); if (eventType === "progress") setProgress({ value: data.value, label: data.label }); if (eventType === "delta") { text += data.text; update({ content: text }); } if (eventType === "answer") update({ content: data.text || text, sources: data.sources, plan: data.plan }); if (eventType === "error") throw new Error(data.message); };
      while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value ?? new Uint8Array(), { stream: !done }); const blocks = buffer.split("\n\n"); buffer = blocks.pop() ?? ""; blocks.forEach(parse); if (done) break; }
      setProgress({ value: 100, label: "Research complete" });
    } catch (error) { setMessages((all) => all.map((item, index) => index === all.length - 1 ? { ...item, content: `I couldn’t complete that request. ${error instanceof Error ? error.message : ""}` } : item)); setProgress({ value: 0, label: "Connection interrupted" }); } finally { setBusy(false); scroll(); }
  }
  return <section className="mx-auto flex min-h-[calc(100vh-70px)] max-w-4xl flex-col px-5 sm:px-8"><div className="flex-1 py-10 sm:py-14"><div className="mb-10 animate-in fade-in slide-in-from-bottom-2 duration-700"><Badge className="border border-rose-300/20 bg-rose-300/10 text-rose-100 hover:bg-rose-300/10"><Activity size={13} className="mr-1.5" /> Live research</Badge><h1 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">Ground answers in operational evidence.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-stone-400">A deliberate workspace for technical investigation—not a generic chat window.</p></div><div className="space-y-7">{messages.map((message, index) => <Message key={`${message.role}-${index}`} value={message} streaming={busy && index === messages.length - 1} />)}</div><div ref={end} /></div><div className="sticky bottom-0 border-t border-stone-800/80 bg-[#0a0f17]/95 py-5 backdrop-blur-xl sm:pb-7">{(busy || progress.value > 0) && <div className="mb-3"><div className="mb-2 flex justify-between text-xs"><span className="font-medium text-rose-100">{progress.label}</span><span className="text-stone-500">{progress.value}%</span></div><Progress value={progress.value} className="h-1.5 bg-stone-800 [&>div]:bg-rose-300" /></div>}<form onSubmit={(event) => ask(event)} className="rounded-2xl border border-stone-700 bg-[#111925] p-2 shadow-[0_16px_45px_rgba(0,0,0,.22)] focus-within:border-stone-500"><Textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); ask(); } }} placeholder="Ask about your knowledge base…" className="min-h-[58px] resize-none border-0 bg-transparent px-3 py-3 text-[15px] text-stone-100 shadow-none placeholder:text-stone-500 focus-visible:ring-0" /><div className="flex items-center justify-between px-1 pb-1"><span className="pl-2 text-xs text-stone-500">Enter to send · Shift + Enter for a new line</span><Button type="submit" size="icon" disabled={!input.trim() || busy} className="h-9 w-9 rounded-xl bg-rose-300 text-stone-950 hover:bg-rose-200"><ArrowUp size={17} /></Button></div></form>{messages.length === 1 && <div className="mt-3 flex flex-wrap gap-2">{suggestions.map((item) => <button key={item} onClick={() => ask(undefined, item)} className="rounded-full border border-stone-800 px-3 py-1.5 text-xs text-stone-400 transition hover:border-stone-600 hover:text-stone-200">{item}</button>)}</div>}</div></section>;
}

function Message({ value, streaming }: { value: Message; streaming: boolean }) { const user = value.role === "user"; return <article className={`flex gap-3 animate-in fade-in slide-in-from-bottom-2 duration-500 ${user ? "justify-end" : ""}`}>{!user && <span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg border border-rose-300/20 bg-rose-300/10 text-rose-200"><Bot size={16} /></span>}<div className={`max-w-[88%] ${user ? "rounded-2xl rounded-tr-md bg-stone-800 px-4 py-3" : "pt-1"}`}>{!user && <p className="mb-2 text-xs font-semibold text-stone-300">Atlas</p>}{value.content ? <p className="whitespace-pre-wrap text-[15px] leading-7 text-stone-200">{value.content}{streaming && <span className="ml-1 inline-block h-4 w-1.5 animate-pulse bg-rose-200 align-[-2px]" />}</p> : <span className="inline-flex gap-1 py-2"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-rose-200" /><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-rose-200 [animation-delay:-.15s]" /></span>}{value.plan && <div className="mt-4 flex flex-wrap gap-1.5">{value.plan.map((step) => <span key={step} className="rounded-md border border-stone-800 bg-stone-900 px-2 py-1 text-[11px] text-stone-400"><Check size={11} className="mr-1 inline text-emerald-400" />{step}</span>)}</div>}{value.sources && <div className="mt-4 grid gap-2">{value.sources.map((source, index) => <details key={`${source.source}-${index}`} className="group rounded-xl border border-stone-800 bg-stone-900/60 px-3 py-2.5"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-medium text-stone-300"><FileText size={14} className="text-rose-200" /><span className="truncate">{source.source}</span><ChevronRight size={14} className="ml-auto text-stone-500 transition group-open:rotate-90" /></summary><p className="mt-2 border-t border-stone-800 pt-2 text-xs leading-5 text-stone-400">{source.content}</p></details>)}</div>}</div></article>; }

function Evaluation() {
  const [dataset, setDataset] = useState<Dataset | null>(null); const [running, setRunning] = useState(false); const [result, setResult] = useState<{ guardrails: { accuracy: number; precision: number; recall: number; total: number } } | null>(null);
  useEffect(() => { fetch(`${API_URL}/eval/dataset`).then((response) => response.ok ? response.json() : null).then(setDataset).catch(() => setDataset(null)); }, []);
  const run = async () => { setRunning(true); try { const response = await fetch(`${API_URL}/eval/run`, { method: "POST" }); if (!response.ok) throw new Error(); setResult(await response.json()); } finally { setRunning(false); } };
  return <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14"><Badge className="border border-rose-300/20 bg-rose-300/10 text-rose-100 hover:bg-rose-300/10"><BarChart3 size={13} className="mr-1.5" /> Quality studio</Badge><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold tracking-[-.035em]">Make quality visible.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-stone-400">Run the live retrieval and safety suite from the same workspace used to demonstrate the product.</p></div><Button onClick={run} disabled={running} className="bg-white text-stone-950 hover:bg-stone-200">{running ? "Running live suite…" : "Run evaluation suite"}</Button></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><Metric label="Retrieval cases" value={dataset ? String(dataset.rag_samples.length) : "—"} detail="Documentation-grounded questions" /><Metric label="Safety cases" value={dataset ? String(dataset.guardrails_samples.length) : "—"} detail="Blocked and permitted inputs" /><Metric label="Guardrail accuracy" value={result ? `${Math.round(result.guardrails.accuracy * 100)}%` : "—"} detail={result ? `${result.guardrails.total} live checks` : "Run suite to measure"} /></div>{running && <div className="mt-7 rounded-2xl border border-stone-800 bg-stone-900/50 p-5"><div className="flex items-center gap-3 text-sm text-stone-300"><CircleDot className="animate-spin text-rose-200" size={17} /> Calling the live pipeline for every evaluation case.</div><p className="mt-2 text-xs leading-5 text-stone-500">This uses the same model, retriever, and guardrails as Research. It can take several minutes.</p></div>}<div className="mt-8 overflow-hidden rounded-2xl border border-stone-800 bg-[#0d131d]"><div className="flex items-center justify-between border-b border-stone-800 px-5 py-4"><div><p className="font-medium">Coverage inventory</p><p className="mt-1 text-xs text-stone-500">Questions used by the live evaluation suite</p></div><Database size={18} className="text-stone-500" /></div><div className="divide-y divide-stone-800">{dataset?.rag_samples.slice(0, 8).map((sample) => <div key={sample.id} className="flex gap-4 px-5 py-4"><span className="grid h-6 w-6 shrink-0 place-items-center rounded bg-stone-800 text-xs text-stone-400">{sample.id}</span><div><p className="text-sm text-stone-200">{sample.question}</p><p className="mt-1 text-xs text-stone-500">{sample.domain.replaceAll("_", " ")}</p></div></div>) ?? <div className="px-5 py-10 text-sm text-stone-500">Connect the API to load the evaluation inventory.</div>}</div></div></section>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-stone-800 bg-[#0d131d] p-5"><p className="text-sm text-stone-400">{label}</p><p className="mt-4 text-3xl font-semibold tracking-tight text-white">{value}</p><p className="mt-2 text-xs text-stone-500">{detail}</p></div>; }

function Ingestion() {
  const [files, setFiles] = useState<File[]>([]); const [sourceType, setSourceType] = useState("general"); const [busy, setBusy] = useState(false); const [results, setResults] = useState<{ filename: string; status: string; chunks?: number; reason?: string }[]>([]);
  const upload = async () => { if (!files.length) return; setBusy(true); const form = new FormData(); files.forEach((file) => form.append("files", file)); form.append("source_type", sourceType); try { const response = await fetch(`${API_URL}/ingest`, { method: "POST", body: form }); const data = await response.json(); setResults(data.results ?? []); } finally { setBusy(false); } };
  return <section className="mx-auto max-w-5xl px-5 py-10 sm:px-8 sm:py-14"><Badge className="border border-rose-300/20 bg-rose-300/10 text-rose-100 hover:bg-rose-300/10"><FolderUp size={13} className="mr-1.5" /> Knowledge intake</Badge><h1 className="mt-4 text-3xl font-semibold tracking-[-.035em]">Bring new evidence into the system.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-stone-400">Upload supported PDFs, Office files, HTML, or text. The pipeline extracts, chunks, embeds, and indexes each document.</p><div className="mt-10 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><label className="group flex min-h-[260px] cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-stone-700 bg-[#0d131d] p-8 text-center transition hover:border-rose-300/50 hover:bg-stone-900/60"><input type="file" multiple accept=".pdf,.html,.htm,.txt,.docx,.pptx" className="sr-only" onChange={(event) => setFiles(Array.from(event.target.files ?? []))} /><span className="grid h-12 w-12 place-items-center rounded-xl border border-stone-700 bg-stone-900 text-rose-200 group-hover:border-rose-300/40"><Upload size={20} /></span><p className="mt-4 font-medium">Select source documents</p><p className="mt-2 max-w-xs text-sm leading-6 text-stone-500">PDF, DOCX, PPTX, HTML, and TXT are supported.</p>{files.length > 0 && <Badge className="mt-5 bg-rose-300 text-stone-950">{files.length} file{files.length === 1 ? "" : "s"} selected</Badge>}</label><div className="rounded-2xl border border-stone-800 bg-[#0d131d] p-5"><p className="font-medium">Indexing settings</p><label className="mt-5 block text-sm text-stone-400">Source group<input value={sourceType} onChange={(event) => setSourceType(event.target.value)} className="mt-2 w-full rounded-lg border border-stone-700 bg-stone-900 px-3 py-2.5 text-sm text-stone-100 outline-none focus:border-rose-300" /></label><p className="mt-4 text-xs leading-5 text-stone-500">Re-uploading a source replaces its prior chunks, so the index stays clean.</p><Button onClick={upload} disabled={!files.length || busy} className="mt-6 w-full bg-rose-300 text-stone-950 hover:bg-rose-200">{busy ? "Indexing documents…" : "Ingest and index"}</Button></div></div>{results.length > 0 && <div className="mt-6 rounded-2xl border border-stone-800 bg-[#0d131d] p-5"><p className="font-medium">Ingestion result</p><div className="mt-4 space-y-2">{results.map((result) => <div key={result.filename} className="flex items-center justify-between rounded-lg bg-stone-900/70 px-3 py-2.5 text-sm"><span className="truncate text-stone-300">{result.filename}</span><span className={result.status === "indexed" ? "text-emerald-400" : "text-rose-300"}>{result.status === "indexed" ? `${result.chunks ?? 0} chunks indexed` : result.reason ?? result.status}</span></div>)}</div></div>}</section>;
}
